'use strict';

/**
 * Application Error Codes
 * Organized by category with numeric prefixes for easy identification
 */

module.exports = {
  // Authentication Errors (1xxx)
  AUTH: {
    OTP_EXPIRED: 'OTP_EXPIRED', // 1001
    OTP_INVALID: 'OTP_INVALID', // 1002
    OTP_MAX_ATTEMPTS: 'OTP_MAX_ATTEMPTS', // 1003
    OTP_RATE_LIMITED: 'OTP_RATE_LIMITED', // 1004
    TOKEN_EXPIRED: 'TOKEN_EXPIRED', // 1005
    TOKEN_INVALID: 'TOKEN_INVALID', // 1006
    SESSION_EXPIRED: 'SESSION_EXPIRED', // 1007
    SESSION_REVOKED: 'SESSION_REVOKED', // 1008
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS', // 1009
    ACCOUNT_BLOCKED: 'ACCOUNT_BLOCKED', // 1010
    ACCOUNT_NOT_VERIFIED: 'ACCOUNT_NOT_VERIFIED', // 1011
    REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID', // 1012
    MFA_REQUIRED: 'MFA_REQUIRED', // 1013
    MFA_INVALID: 'MFA_INVALID', // 1014
  },

  // Authorization Errors (2xxx)
  AUTHORIZATION: {
    FORBIDDEN: 'FORBIDDEN', // 2001
    INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS', // 2002
    RESOURCE_NOT_OWNED: 'RESOURCE_NOT_OWNED', // 2003
    ORG_ACCESS_DENIED: 'ORG_ACCESS_DENIED', // 2004
    ADMIN_REQUIRED: 'ADMIN_REQUIRED', // 2005
    ROLE_REQUIRED: 'ROLE_REQUIRED', // 2006
  },

  // Validation Errors (3xxx)
  VALIDATION: {
    VALIDATION_ERROR: 'VALIDATION_ERROR', // 3001
    INVALID_PHONE: 'INVALID_PHONE', // 3002
    INVALID_EMAIL: 'INVALID_EMAIL', // 3003
    INVALID_FILE_TYPE: 'INVALID_FILE_TYPE', // 3004
    FILE_TOO_LARGE: 'FILE_TOO_LARGE', // 3005
    MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD', // 3006
    INVALID_PRICE: 'INVALID_PRICE', // 3007
    INVALID_LOCATION: 'INVALID_LOCATION', // 3008
    INVALID_DATE: 'INVALID_DATE', // 3009
    INVALID_FORMAT: 'INVALID_FORMAT', // 3010
  },

  // Resource Errors (4xxx)
  RESOURCE: {
    NOT_FOUND: 'NOT_FOUND', // 4001
    PROPERTY_NOT_FOUND: 'PROPERTY_NOT_FOUND', // 4002
    USER_NOT_FOUND: 'USER_NOT_FOUND', // 4003
    ORG_NOT_FOUND: 'ORG_NOT_FOUND', // 4004
    LEAD_NOT_FOUND: 'LEAD_NOT_FOUND', // 4005
    MEDIA_NOT_FOUND: 'MEDIA_NOT_FOUND', // 4006
    PACKAGE_NOT_FOUND: 'PACKAGE_NOT_FOUND', // 4007
    SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND', // 4008
    ALREADY_EXISTS: 'ALREADY_EXISTS', // 4009
    DUPLICATE_ENTRY: 'DUPLICATE_ENTRY', // 4010
    PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND', // 4011
    SESSION_NOT_FOUND: 'SESSION_NOT_FOUND', // 4012
    TEMPLATE_NOT_FOUND: 'TEMPLATE_NOT_FOUND', // 4013
  },

  // Business Logic Errors (5xxx)
  BUSINESS: {
    INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION', // 5001
    PROPERTY_NOT_DRAFT: 'PROPERTY_NOT_DRAFT', // 5002
    PROPERTY_ALREADY_PUBLISHED: 'PROPERTY_ALREADY_PUBLISHED', // 5003
    MODERATION_PENDING: 'MODERATION_PENDING', // 5004
    SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED', // 5005
    LISTING_LIMIT_REACHED: 'LISTING_LIMIT_REACHED', // 5006
    PAYMENT_FAILED: 'PAYMENT_FAILED', // 5007
    COUPON_INVALID: 'COUPON_INVALID', // 5008
    COUPON_EXPIRED: 'COUPON_EXPIRED', // 5009
    KYC_PENDING: 'KYC_PENDING', // 5010
    ORG_NOT_VERIFIED: 'ORG_NOT_VERIFIED', // 5011
    INSUFFICIENT_CREDITS: 'INSUFFICIENT_CREDITS', // 5012
    OPERATION_NOT_ALLOWED: 'OPERATION_NOT_ALLOWED', // 5013
    ALREADY_CLAIMED: 'ALREADY_CLAIMED', // 5014
    PROPERTY_EXPIRED: 'PROPERTY_EXPIRED', // 5015
  },

  // System Errors (9xxx)
  SYSTEM: {
    INTERNAL_ERROR: 'INTERNAL_ERROR', // 9001
    SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE', // 9002
    DATABASE_ERROR: 'DATABASE_ERROR', // 9003
    CACHE_ERROR: 'CACHE_ERROR', // 9004
    EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR', // 9005
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED', // 9006
    TIMEOUT: 'TIMEOUT', // 9007
    KAFKA_ERROR: 'KAFKA_ERROR', // 9008
    ELASTICSEARCH_ERROR: 'ELASTICSEARCH_ERROR', // 9009
  },
};
